# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application



on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: exec ssh
      uses: appleboy/ssh-action@master
      with: 
        host: 165.22.68.194
        username: root
        password: ${{secrets.PSWRD}}
        port: 22
        script: |
          cd /var/www/microservices_devops/
          source venv/bin/activate
          git pull origin main
          pip install -r requirements.txt
          supervisorctl restart get_users
          supervisorctl restart insert_users
          supervisorctl restart notify_users
          supervisorctl restart complete_users
    - name: Run tests and collect coverage
      run: pytest --cov=tests  --cov-report=xml
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
